apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ddasick/byulassign:msa-user-service
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:log4jdbc:mysql://mysql-service:3306/msa_member?serverTimezone=UTC&characterEncoding=utf8
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: user-service
      protocol: TCP
      port: 8082
      targetPort: 8082
      