apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-list-role
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "endpoints"]
    verbs: ["list", "get", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-list-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: service-list-role
  apiGroup: rbac.authorization.k8s.io