server:
  port: 8082

spring:
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        enabled: true
  application:
    name: user-service
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/msa_member?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 1234

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis:
  mapper-locations: classpath:mapper/*.xml